### ISSUE TITLE
How to use the config service to configure other modules?

### ISSUE THREAD

**Issue by gremo** [nestjs-community/nestjs-config#19]
Great library, but I'm having issues using the `ConfigService` to configure other modules. Can you provide some example?

**Comment by bashleigh** [comment]
I've been struggling with this one myself if I'm honest. I have been following an issue you recently commented on https://github.com/nestjs/nest/issues/530. 
I've been experimented but I've recently stopped due to my work load. I haven't yet tried using the decorators however I don't think they're the solution to this problem because the problem still persists that the config module is not loaded before another module. 

```ts
import {Module, DynamicModule} from 'nestjs/common';
import {Configurable, ConfigParam} from 'nestjs-config';

@Module({
    imports: [ConfigModule],
})
export default class DatabaseModule {

    @configurable()
    public function forRoot(@ConfigParam('db.name') name: string, @ConfigParam('db.port') port: number, @ConfigParam('db.host') host: string): DynamicModule {
        return {
            module: DatabaseModule,
            imports: [TypeOrmModule.forRoot({
                host,
                name,
                port,
           })],
        };
    }
}
```

```ts
import DatabaseModule from './database.module';
import {Module} from '@nestjs/common';

@Module({
    imports: [ConfigModule.load(), DatabaseModule],
})
export AppModule {}
```

I'm really doubtful that this will work. Would be cool if it did but unfortunately nestjs doesn't offer the ability for a module to 'depend on' another module currently. I'm hoping the methodology will be similar to that of the asyncProvider but right now I'm just waiting to see what the project owner decides.

**Comment by gremo** [comment]
@bashleigh you are not calling `forRoot` of your database module, I don't think this is going to work 🤕

**Comment by gremo** [comment]
@bashleigh It doesn't work. Even if we ignore the fact that `forRoot` actually requires arguments, and we are not padding them, injection doesn't work.

**Comment by bashleigh** [comment]
I didn't think it would sorry. I'll keep an eye on that issue and see if any comes of it. I'll close this issue for now and reopen when and if an answer is available

**Comment by bashleigh** [comment]
After discussing this with @fenos last night it would be possible to do the following in theory. 

```ts
//app.module
import {ConfigModule} from './config.module';
import {ConfigService} from 'nestjs-config';
import {Module} from '@nestjs/common';

const configService = new ConfigService();
await configService.load(); //add your load settings

@Module({
    imports: [ConfigModule.loadConfigService(configService)]
})
export class AppModule {}
```

```ts
//config.module
import {ConfigService} from 'nestjs-config';
import {Module, DynamicModule} from '@nestjs/common';

@Module({})
export class ConfigModule extends ConfigModule {
    public static loadConfigModule(configService: ConfigService): DynamicModule {
        return {
            module: ConfigModule,
            providers: [ConfigService],
            exports: [ConfigService],
        };
    }
}
```

The idea here is we're loading the config service before the container starts and inserting the new class into a 'custom' defined ConfigModule that requires the configservice to be passed in rather than loaded within the module itself therefore loading the config before all modules 👍 hope this helps! 

We are watching what happens with the issue on nestjs to see what the decision is. After a decision is made we'll act on it and update the config module accordingly.

**Comment by gremo** [comment]
>... that requires the configservice to be passed in rather than loaded within the module itself therefore loading the config before all modules

I was thinking about the a few days ago. Ugly solution IMHO.

I hope that the issue on nestjs will be solved. In the end, it's all about modules depending on services (@marcus-sa solution):

```typescript
@Module({
  imports: [{
    useModule: (config: ConfigService) => MongooseModule.forRoot(config.mongoUri),
    inject: [ConfigService]
  }],
  providers: [ConfigService],
})
export class AppModule { }
```

**Comment by FerreiraBruno13** [comment]
Well i just bumped into this problem and found a solution in the [NestJS docs](https://docs.nestjs.com/techniques/http-module#async-configuration)

This uses async configuration inside the module imports

**Comment by EthanSchoen** [comment]
For anyone here from google like me this is what I needed:

`@Module({
  imports: [
    MongooseModule.forRootAsync({
      useFactory: (configService: ConfigService) => ({
        uri: configService.get('MONGO_DB_URL'),
      }),
      inject: [ConfigService],
    }),
  ],
  providers: [ConfigService],
})
export class AppModule {}`
