### ISSUE TITLE
ConfigModule.resolveSrcPath prints warning

### ISSUE THREAD

**Issue by Diluka** [nestjs-community/nestjs-config#76]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**nestjs-config version**

**@nestjs/common+core or other package versions**
 - @nestjs/common: 
 - @nestjs/core: 

#### Replication/Example

```ts
ConfigModule.resolveSrcPath(__dirname).load('config/**/!(*.d).{ts,js}', { path: envPath }),
```

https://github.com/nestjs-community/nestjs-config/blob/8ebfa857feb6be3004e8fda1a4697eda2476c2b0/src/module/config.module.ts#L7-L10

https://github.com/nestjs-community/nestjs-config/blob/8ebfa857feb6be3004e8fda1a4697eda2476c2b0/src/module/config.service.ts#L186-L226

```log
  console.log node_modules/nestjs-config/dist/module/config.service.js:180
    WARNING: Method 'resolveSrcPath' has been deprecated. Please use 'resolveRootPath'
```

**Is there any way else to config the root path?**

**Comment by bashleigh** [comment]
That's embarrassing... I forgot to add the method to configModule.

**Comment by Diluka** [comment]
What is the different between `resolveRootPath` and `resolveSrcPath`? And why not to use [`app-root-path`](https://www.npmjs.com/package/app-root-path)?

**Comment by bashleigh** [comment]
There isn't a difference however I thought maybe people would find the method name misleading similar to the glob pattern example I had in the readme previously. 
I made the change because 'root' could be anything for the config module. Could be `src` could be `dist` could be `package` could even be `~/configs` or however one decides to organise their application or server. I didn't want the term `src` in the method name to be confused with just the `src` directory (like I had done before) so I thought `root` was a better replacement and to be fair, both methods were incredibly similar so I thought why not merge them and kill off the confusing/misleading method name
